bowang-added two new components: popover & speeddial
ploomber/dash-mui pull request #11
Opened 2024-11-04 21:09 UTC by bowang-ynd

Add two new components to dash-mui

working towards #1

2024-11-04 22:36 UTC, LatentDream requested changes

2024-11-04 22:36 UTC, LatentDream commented on src/lib/components/CustomSpeedDial.react.js
> +const iconMap = {
The user can only use those 3 icons. Is there a way to have more ?
Like all for the one from `@mui/icons-material/*`

2024-11-04 22:36 UTC, LatentDream commented on demo/pages/popover.py
> +    mui.Grid(
Same for this one: A lot of white space, and the code is cramp in the corner:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/76700790-5d2c-4364-9f6f-7002313baa8d">

2024-11-06 17:26 UTC, bowang-ynd commented
@LatentDream I have changed the code example size and now the popover and speed dial should take full size of the space now. I also included all icons from the @mui/icons-material now

2024-11-06 18:45 UTC, edublancas commented
@LatentDream please re review

2024-11-06 20:40 UTC, LatentDream approved these changes
I'm suggesting adding a comment about where the user can check the all available icon. Otherwise, Looking good! and Tested on my side

2024-11-06 20:40 UTC, LatentDream commented on demo/pages/speedDial.py
> +    {"id": "save-action", "icon": "Save", "tooltip": "Save"},
```suggestion
speed_dial_actions = [
    # Material UI icons can be used by their names
    # Browse available icons at: https://mui.com/material-ui/icons
    {"id": "save-action", "icon": "Save", "tooltip": "Save"},
```

2024-11-06 21:26 UTC, edublancas commented on demo/pages/speedDial.py
> +    {"id": "save-action", "icon": "Save", "tooltip": "Save"},
@bowang-ynd please apply this change

2024-11-06 21:32 UTC, bowang-ynd commented
@edublancas @LatentDream I have committed the changes to add a quick comment for users to look for icons doc and their names.

2024-11-06 21:38 UTC, merged